<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="XtsTrackStub" Id="{9bbdc397-a1f7-4a22-bd28-c8ebf47c132d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK XtsTrackStub IMPLEMENTS I_XtsTrack
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	_trackLength : MC_LREAL  := 1000;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="MyOTCID" Id="{82e92a1c-ecd4-4993-863a-3adb035740db}">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY MyOTCID : OTCID
]]></Declaration>
      <Get Name="Get" Id="{d8839110-2373-4ef4-848a-6531a30d1bca}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{2a4232e3-ad71-45d8-9e93-375892f77c94}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Property Name="TrackLength" Id="{fa20ce29-545f-440e-8f6d-875dc2b61ead}">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY TrackLength : MC_Lreal
]]></Declaration>
      <Get Name="Get" Id="{24c356d3-cb16-44c5-8eb7-15f581e09659}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[tracklength := _trackLength;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <LineIds Name="XtsTrackStub">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="XtsTrackStub.MyOTCID.Get">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="XtsTrackStub.MyOTCID.Set">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="XtsTrackStub.TrackLength.Get">
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>