<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="XtsTrackStub" Id="{03c15466-6090-4765-816b-ccda66b9b333}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK XtsTrackStub IMPLEMENTS I_XtsTrack
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	_trackLength : MC_LREAL  := 1000;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="MyOTCID" Id="{58d1505c-0536-4521-b091-1fd2d7ec90a0}">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY MyOTCID : OTCID
]]></Declaration>
      <Get Name="Get" Id="{942d4dc2-14a4-4bef-a1f1-3c53554951f2}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{3cae8b1f-6357-4ce3-be2f-9aa0e3e4f6bb}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Property Name="TrackLength" Id="{6b606c91-c693-4cef-8de3-8222ee49a6d2}">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY TrackLength : MC_Lreal
]]></Declaration>
      <Get Name="Get" Id="{2e912149-8443-4ed1-8754-35c8863e5c66}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[tracklength := _trackLength;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <LineIds Name="XtsTrackStub">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="XtsTrackStub.MyOTCID.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="XtsTrackStub.MyOTCID.Set">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="XtsTrackStub.TrackLength.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>