<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="XtsMover" Id="{685c76f7-4dc2-4b6a-8a2f-28de7d2e22ba}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK XtsMover
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="XtsMover">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>