<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="CyclicBase" Id="{822a4270-a76d-44ce-8055-ee2099020175}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT CyclicBase IMPLEMENTS ICyclic
VAR
	Logger : TcMessage_Ext;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[{analysis -2}]]></ST>
    </Implementation>
    <Method Name="Cycle" Id="{9762b721-7f92-40df-8e44-4acdbac204f1}">
      <Declaration><![CDATA[METHOD PUBLIC ABSTRACT Cycle : HRESULT
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[{analysis -2}]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="CyclicBase">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="CyclicBase.Cycle">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>