<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="TmsMoverSequence" Id="{d0a7936d-1617-4a79-aef0-0b298f1ee6e2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TmsMoverSequence
VAR_INPUT
	ThisMover : IMover;
	XtsTrack : IXtsTrack;
	StateMachine : IPmlStateMachine;
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="TmsMoverSequence">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>