<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="FB_Station" Id="{f7551307-30e4-45a3-8d86-064d6f4dc85f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Station IMPLEMENTS IStation
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Position" Id="{58d786ef-bb06-404f-ad6b-347e4198ad75}">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY Position : MC_LREAL
]]></Declaration>
      <Get Name="Get" Id="{34e970be-445e-41f4-a75a-b605d68f84ef}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{dd9d06f8-8d66-4d3d-86ac-5775c8752e45}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <LineIds Name="FB_Station">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Station.Position.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_Station.Position.Set">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>