<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="FB_Station" Id="{f7551307-30e4-45a3-8d86-064d6f4dc85f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Station IMPLEMENTS IStation
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Station">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>