<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="PML_UdefinedState" Id="{01122847-2515-4c38-9336-f3153f26aa0b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PML_UdefinedState
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PML_UdefinedState">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>