<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="TmsExchange" Id="{27fb18f6-f27b-4462-bf40-a5ac4ef58917}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PUBLIC TmsExchange EXTENDS Process
VAR_INPUT
	TmsSwitch : ITF_TmsSwitch;
END_VAR
VAR_OUTPUT
END_VAR
VAR
	movers : ARRAY[1..3] OF ITmsMover;
	StationLocation : INT := 1; //1 = low, 2 = high
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//Station for tms handling
//these are implemented at each entry to the switch

//Do i have mover?
////Do i have switch?
//////If yes pass mover to switch
//////If mover on switch send switch
//////once station done bring rear mover forward
////Else 
//////Wait for switch
//Else
////Wait for movers
]]></ST>
    </Implementation>
    <LineIds Name="TmsExchange">
      <LineId Id="9" Count="1" />
      <LineId Id="61" Count="0" />
      <LineId Id="21" Count="0" />
      <LineId Id="62" Count="7" />
      <LineId Id="77" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>