<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="TmsExchange" Id="{27fb18f6-f27b-4462-bf40-a5ac4ef58917}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PUBLIC TmsExchange EXTENDS Process
VAR_INPUT
	TmsSwitch : ITF_TmsSwitch;
END_VAR
VAR_OUTPUT
END_VAR
VAR
	holdingStation : TmsHoldStation;
	embarkStation : TmsEmbarkStation;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[holdingStation();
embarkStation();
]]></ST>
    </Implementation>
    <LineIds Name="TmsExchange">
      <LineId Id="69" Count="0" />
      <LineId Id="100" Count="0" />
      <LineId Id="77" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>