<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="XtsTrackManager" Id="{bd7124a2-640c-4b46-b298-87b62f0a23a9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK XtsTrackManager
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="XtsTrackManager">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>