<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="XtsManager" Id="{2fa384c0-e3f2-4619-9178-5f62167e09ec}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK XtsManager
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="XtsManager">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>