<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="XtsMoverManager" Id="{4b45940e-4817-4260-a891-e07dd3ca95d8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK XtsMoverManager
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="XtsMoverManager">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>