<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="XTSHardware_V2" Id="{2082c175-1a19-4a3f-b920-8dbd46477756}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK XTSHardware_V2 EXTENDS CyclicBase
VAR
	XtsParts : ARRAY[1..SystemParameters.NumberOfParts] OF XtsPart;
	XtsTracks : ARRAY[1..SystemParameters.NumberOfTracks] OF XtsTrack;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="XTSHardware_V2">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>